# Generated by Django 5.0.3 on 2024-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_home", "0002_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
